### ISSUE TITLE
Icon picker use a font that is not available

### ISSUE THREAD

**Issue by rabol** [Laravel-Backpack/Demo#95]
# Bug report

### What I did:
Installed the Demo
### What I expected to happen:
Icon picker to work
### What happened:
Icons are not shown

this is the console error: 
### What I've already tried to fix it:
this is the problem:
in file: /vendor/backpack/crud/src/resources/views/crud/fields/icon_picker.php

$fontIconFilePath = asset('packages/bootstrap-iconpicker/icon-fonts/font-awesome-5.10.1/css/all.min.css');

the font file is not available

### Backpack, Laravel, PHP, DB version:
The version that the demo installs

**Comment by FrodeMMeling** [comment]
This is easily solved by enabling font-awesome.
go to: `config/backpack/base.php` and uncomment line 54:
`'https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.2/css/all.min.css',`

**Comment by pxpm** [comment]
Hi guys thanks for spoting this out, i think @FrodeMMeling solution does not solve the problem, just masks it.
 
When uncommenting the line the icons apear in the picker but the error persists in console.
 
Could you confirm that @FrodeMMeling ?

Thanks in advance,
Pedro

**Comment by vonsogt** [comment]
you should make sure the version of font-awesome is same as it defined at source

check your version in here:
`https://github.com/Laravel-Backpack/CRUD/blob/master/src/resources/views/crud/fields/icon_picker.blade.php#L29`

after you change the version that you wanted:
download and copy this webfonts folder to your public directory
https://github.com/FortAwesome/Font-Awesome

**Comment by tabacitu** [comment]
@vonsogt 's PR has been merged into 4.1, along with using ```la la-home``` syntax for LineAwesome instead of ```fa fa-home```. That way we avoid any conflicts going further. Thanks again for submitting it! 

Unfortunately the fix has to be pushed as a breaking change. Until then, his solution above should work. Closing this since it's solved with Laravel-Backpack/CRUD#2363
